### PR TITLE
MVP-80: Create Update Image Tag Wiki Table Python Script

### PR DESCRIPTION
**Pull request by akroon3r**
## 🎯 Summary

  
[MVP-80](https://citz-imb.atlassian.net/browse/MVP-80)

## 🔰 Checklist

- [x] I have read and agree with the following checklist and am following the guidelines in our [Code of Conduct](/CODE_OF_CONDUCT.md) document.

> - I have performed a self-review of my code.
> - I have commented my code, particularly in hard-to-understand areas.
> - I have made corresponding changes to the documentation where required.
> - I have tested my changes to the best of my ability.
> - I have consulted with the team if introducing a new dependency.
> - My changes generate no new warnings.

### CODE REVIEW

**Comment by akroon3r** [comment]
> Did you mean to create this under the `github-api` subdirectory of `.github/helpers` ?

Just following the path example set in PIMS by Manish.

**Comment by BradyMitch** [comment]
> > Did you mean to create this under the `github-api` subdirectory of `.github/helpers` ?
> 
> Just following the path example set in PIMS by Manish.

In pims the path was under `helpers/`, not `helpers/github-api/`

**Review by TaylorFries — APPROVED** [review]

**Comment by akroon3r** [comment]
whoopsie, fixed.

**Comment by akroon3r** [comment]
Forgot to change branches ignore that file added and deleted please.

**Review by BradyMitch — APPROVED** [review]

**Pull request merged**
